# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Multi-Plex Experiment
#' 
#' Run mPlex experiments, choosing the type of inheritance desired.
#' 
#' @examples
#' \dontrun{
#' nope
#' none
#' sorry
#' }
#' 
#' 
run_mPlex_Cpp <- function(seed, networkParameters_, reproductionReference_, migrationMale_, migrationFemale_, migrationBatch_, reproductionType_, verbose) {
    invisible(.Call('_mPlexCpp_run_mPlex_Cpp', PACKAGE = 'mPlexCpp', seed, networkParameters_, reproductionReference_, migrationMale_, migrationFemale_, migrationBatch_, reproductionType_, verbose))
}

