# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
unit_test_PRNG <- function(seed) {
    invisible(.Call('_mPlexCpp_unit_test_PRNG', PACKAGE = 'mPlexCpp', seed))
}

rcpp_hello_world <- function() {
    .Call('_mPlexCpp_rcpp_hello_world', PACKAGE = 'mPlexCpp')
}

