###############################################################################
#    __  __       _ _   _       _                      _                         
#   |  \/  |_   _| | |_(_)_ __ | | _____  __      ___ | |    ___   ___ _   _ ___ 
#   | |\/| | | | | | __| | '_ \| |/ _ \ \/ /____ / _ \| |   / _ \ / __| | | / __|
#   | |  | | |_| | | |_| | |_) | |  __/>  <_____| (_) | |__| (_) | (__| |_| \__ \
#   |_|  |_|\__,_|_|\__|_| .__/|_|\___/_/\_\     \___/|_____\___/ \___|\__,_|___/
#                        |_|                                                     
###############################################################################


#play with stuff until a generating function works.
# one locus, multiple targets at that locus, gives many types of alleles

#assume the inputs are 
#this tells me there are 3 sites, with 2 potential resistant alleles, and background mutation
## 

###############################################################################
# Functions for actual use
###############################################################################

MakeReferenceMultiplex_oLocus <- function(H=c(0.9),R=c(0.0), S=R/3, d=c(0.0001)){
  #H is homing rate. The length of this vector determines the number of loci 
  # in the multiplex drive. Each drive can have the same or different rates. 

  #R is the NHEJ rate for deleterious alleles. Must be same length as H, 
  # can be the same or different values.
                            
  #S is the NHEJ rate for neutral alleles. Must be the same length as H, 
  # can be the same or different values.
  
  #d is the background mutation rate. Must be the same length as H, can
  # have the same or different values.
  
  gtype <- c("W", "H", "R", "S")

  #matrix to hold homing probs, then fill it
  homingProbs <- matrix(data = 0, nrow = 4, ncol = length(H), dimnames = list(gtype, NULL))

  homingProbs[1, ] <- 1-d-H #chance to stay W is 1-homing-background mutation
  homingProbs[2, ] <- H*(1-R-S) #chance to become homing is H*1-H*R-H*S
  homingProbs[3, ] <- H*R   #NHEJ caused resistance, detrimentalt allele
  homingProbs[4, ] <- d+H*S #good resistant allele, from NHEJ and background mutation rate
  
  #set up lists to hold probabilities
  mendProbsList <- vector(mode = "list", length = length(H))
  homProbsList <- vector(mode = "list", length = length(H))
  
  #fill the lists
  for(i in 1:length(H)){
    #Mendelian Probabilities
    mendProbsList[[i]]$W <- setNames(object = c(1-d[i], d[i]), nm = c("W", "S"))
    mendProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    mendProbsList[[i]]$R <- 1
    mendProbsList[[i]]$S <- 1

    #Homing Probabilities
    homProbsList[[i]]$W <- homingProbs[ ,i]
    homProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    homProbsList[[i]]$R <- 1
    homProbsList[[i]]$S <- 1
  }
  
  return(list(
    mendelian = mendProbsList, 
    homing = homProbsList))
  
} 


MultiplexOffspring_oLocus <- function(fGen, mGen, reference){
  #fGen is mother genotype
  #mGen is fathers genotype
  #reference is list of lists generated by MakeReference
  if(nchar(fGen) != nchar(mGen)){
    return(cat("Critters have different number of loci.\nCheck their genotypes."))
  }
  
  #split genotypes
  #This splits all characters.
  fSplit <- strsplit(x = fGen, split = "")[[1]]
  mSplit <- strsplit(x = mGen, split = "")[[1]]
  
  #get number of alleles. Divide by 2 is because diploid
  nHom <- length(fSplit)/2
  
  #the paste statement combines all targets in the first loci and all targets 
  #  in the second loci into 2 complete alleles
  fmPlex <- list(allele1 = fSplit[1:nHom], allele2 = fSplit[(nHom+1):(2*nHom)] )
  mmPlex <- list(allele1 = mSplit[1:nHom], allele2 = mSplit[(nHom+1):(2*nHom)] )
  
  #score them, assumes fGen and mGen are 1 character string, not a list of things
  #  If I stop pasting alleles together, we may have to change this!!
  fScore <- grepl(pattern = "H", x = fGen, ignore.case = FALSE, perl = FALSE, fixed = TRUE)
  mScore <- grepl(pattern = "H", x = mGen, ignore.case = FALSE, perl = FALSE, fixed = TRUE)
  
  #setup offspring allele lists
  # assuem diploid organism with nHom homing sites
  fAllele <- rep(x = list(vector(mode = "list", nHom)), 2)
  fProbs <- rep(x = list(vector(mode = "list", nHom)), 2)
  mAllele <- rep(x = list(vector(mode = "list", nHom)), 2)
  mProbs <- rep(x = list(vector(mode = "list", nHom)), 2)
  
  #Females!
  if(fScore) {
    #if homing allele present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:nHom){
        #Fill target with letter and probs
        if(fmPlex[[i]][[j]]=="W"){
          fAllele[[i]][[j]] <- c("W","H","R","S")
          fProbs[[i]][[j]] <- reference$homing[[j]]$W
        } else if(fmPlex[[i]][[j]]=="H"){
          fAllele[[i]][[j]] <- c("H", "S")
          fProbs[[i]][[j]] <- reference$homing[[j]]$H
        } else if(fmPlex[[i]][[j]]=="R"){
          fAllele[[i]][[j]] <- "R"
          fProbs[[i]][[j]] <- reference$homing[[j]]$R
        } else if(fmPlex[[i]][[j]]=="S"){
          fAllele[[i]][[j]] <- "S"
          fProbs[[i]][[j]] <- reference$homing[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
    
  } else {
    #if homing allele not present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:nHom){
        #Fill target with letter and probs
        if(fmPlex[[i]][[j]]=="W"){
          fAllele[[i]][[j]] <- c("W","S")
          fProbs[[i]][[j]] <- reference$mendelian[[j]]$W
        } else if(fmPlex[[i]][[j]]=="H"){
          fAllele[[i]][[j]] <- c("H", "S")
          fProbs[[i]][[j]] <- reference$mendelian[[j]]$H
        } else if(fmPlex[[i]][[j]]=="R"){
          fAllele[[i]][[j]] <- "R"
          fProbs[[i]][[j]] <- reference$mendelian[[j]]$R
        } else if(fmPlex[[i]][[j]]=="S"){
          fAllele[[i]][[j]] <- "S"
          fProbs[[i]][[j]] <- reference$mendelian[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
  }#end Female if statement
  
  #Males!
  if(mScore) {
    #if homing allele present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:nHom){
        #Fill target with letter and probs
        if(mmPlex[[i]][[j]]=="W"){
          mAllele[[i]][[j]] <- c("W","H","R","S")
          mProbs[[i]][[j]] <- reference$homing[[j]]$W
        } else if(mmPlex[[i]][[j]]=="H"){
          mAllele[[i]][[j]] <- c("H", "S")
          mProbs[[i]][[j]] <- reference$homing[[j]]$H
        } else if(mmPlex[[i]][[j]]=="R"){
          mAllele[[i]][[j]] <- "R"
          mProbs[[i]][[j]] <- reference$homing[[j]]$R
        } else if(mmPlex[[i]][[j]]=="S"){
          mAllele[[i]][[j]] <- "S"
          mProbs[[i]][[j]] <- reference$homing[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
    
  } else {
    #if homing allele not present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:nHom){
        #Fill target with letter and probs
        if(mmPlex[[i]][[j]]=="W"){
          mAllele[[i]][[j]] <- c("W","S")
          mProbs[[i]][[j]] <- reference$mendelian[[j]]$W
        } else if(mmPlex[[i]][[j]]=="H"){
          mAllele[[i]][[j]] <- c("H", "S")
          mProbs[[i]][[j]] <- reference$mendelian[[j]]$H
        } else if(mmPlex[[i]][[j]]=="R"){
          mAllele[[i]][[j]] <- "R"
          mProbs[[i]][[j]] <- reference$mendelian[[j]]$R
        } else if(mmPlex[[i]][[j]]=="S"){
          mAllele[[i]][[j]] <- "S"
          mProbs[[i]][[j]] <- reference$mendelian[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
  }#end Female if statement
  
  

  
  
  
  fAKids <- vector(mode = "list", length = 2)
  fPKids <- vector(mode = "list", length = 2)
  mAKids <- vector(mode = "list", length = 2)
  mPKids <- vector(mode = "list", length = 2)
  
  
  for(i in 1:2){
    #expand female alleles and probs
    fAHold <- expand.grid(fAllele[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    fPHold <- expand.grid(fProbs[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    
    #expand male alleles and probs
    mAHold <- expand.grid(mAllele[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    mPHold <- expand.grid(mProbs[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    
    #paste things in reverse
    fAKids[[i]] <- do.call(what = paste0, c(fAHold[, nHom:1,drop=FALSE], collapse = NULL))
    fPKids[[i]] <- apply(X = fPHold, MARGIN = 1, FUN = prod)
    
    mAKids[[i]] <- do.call(what = paste0, c(mAHold[, nHom:1,drop=FALSE], collapse = NULL))
    mPKids[[i]] <- apply(X = mPHold, MARGIN = 1, FUN = prod)
    
  }
  
  #unlist so that alleles within parent don't combine, then expand all
  #  combinations of male/female alleles
  ExpandedGenotypes <- expand.grid(unlist(fAKids), unlist(mAKids), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  ExpandedGenotypeProbs <- expand.grid(unlist(fPKids), unlist(mPKids), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  
  
  CollapsedGen <- do.call(what = paste0, c(ExpandedGenotypes, collapse = NULL))
  CollapsedGenProbs <- apply(X = ExpandedGenotypeProbs, MARGIN = 1, FUN = prod)
  #could do hold[,1]*hold[,2]
  
  #aggregate and return
  finalHold <- aggregate(CollapsedGenProbs~CollapsedGen, data=data.frame(CollapsedGen, CollapsedGenProbs), FUN=sum)
  
  #get proper type and normalize, then return as list.
  return(list(
    Alleles = as.character(finalHold$CollapsedGen),
    Probabilities = finalHold$CollapsedGenProbs/sum(finalHold$CollapsedGenProbs)
  ))
  
}










###############################################################################
# Original Function
###############################################################################

#given the alleles, this will create a vector of all unique genotypes, and 
#  fill a cube as traditionally used in MGDrivE

Multiplex_FULL <- function(H=c(0.9, .6), R=0.0001, S=R/3, d=0.0001){
  #     H=homing alleles, given as a vector of homing rate. The length of that
  #         vector is the multiplex number
  #     R=resistant allele, damaging, from NHEJ
  #     S=resistant allele, not damaging, from NHEJ. defined as 1/3 the rate of R
  #     d=background mutations
  
  gtype <- c("W", "H", "R", "S")
  
  library("gtools")
  library("stringi")
  library("matrixStats")
  
  #experimental
  library("slam")
  library(tractor.base)
  
  
  ###############################################################################
  #generate all genotypes, set up vectors and matrices
  
  #gets all allele possibilities.
  # expand.grid is faster, but requires a list.
  openGtype <- gtools::permutations(n = length(gtype),r =length(H) ,v = gtype, set = FALSE, repeats.allowed = TRUE )
  
  #convert to list, openGtype is not always the same dimension
  # ncol() is always equal to length(H)
  openGtype <- lapply(X = seq_len(length.out = ncol(openGtype)), FUN = function(i){openGtype[,i]})
  
  #stitch the alleles together
  alleleType <- do.call(what = stringi::stri_join, args = openGtype)
  
  #get all possible combinations of allelles, always some rows by 2 columns
  openAllele <- gtools::combinations(n = length(alleleType), r = 2, v = alleleType, set = FALSE, repeats.allowed = TRUE)
  
  #final allele combinations
  genotypes <- do.call(what = stringi::stri_join, args = list(openAllele[,1], openAllele[,2]))
  
  #create a thing to see if this works
  #these work for H=2
  setNames(object = numeric(length(genotypes)), nm = genotypes)
  matrix(data = 0, nrow = length(genotypes), ncol = length(genotypes), dimnames = list(genotypes, genotypes))
  tMatrix <- array(data = 0, dim = c(length(genotypes),length(genotypes),length(genotypes)), dimnames = list(genotypes,genotypes,genotypes))
  
  
  ###############################################################################
  #setup all probability matrices
  
  #matrix to hold homing probs, then fill it
  homingProbs <- matrix(data = 0, nrow = 4, ncol = length(H), dimnames = list(gtype, NULL))
  
  homingProbs[1, ] <- 1-d-H #chance to stay W is 1-homing-background mutation
  homingProbs[2, ] <- H*(1-R-S) #chance to become homing is H*1-H*R-H*S
  #homing probs, - NHEJ probs
  homingProbs[3, ] <- H*R   #NHEJ caused resistance, detrimentalt allele
  homingProbs[4, ] <- d+H*S #good resistant allele, from NHEJ and background mutation rate
  
  #set up lists to hold probabilities
  homProbsList <- vector(mode = "list", length = length(H))
  noHomProbsList <- vector(mode = "list", length = length(H))
  
  #fill the lists
  for(i in 1:length(H)){
    homProbsList[[i]]$W <- homingProbs[,i]
    homProbsList[[i]]$H <- setNames(object = c(1-d,d), nm = c("H", "S"))
    homProbsList[[i]]$R <- 1
    homProbsList[[i]]$S <- 1
    
    noHomProbsList[[i]]$W <- setNames(object = c(1-d,d), nm = c("W", "S"))
    noHomProbsList[[i]]$H <- setNames(object = c(1-d,d), nm = c("H", "S"))
    noHomProbsList[[i]]$R <- 1
    noHomProbsList[[i]]$S <- 1
  }
  
  ###############################################################################
  #fill transition matrix
  
  #check if homing allele is present
  hCheck <- grepl(pattern = "H", x = genotypes, ignore.case = FALSE, perl = FALSE, fixed = TRUE)
  nHom <- length(H)
  
  #loop over all matings, male and female
  for (fi in 1:length(genotypes)){
    for (mi in 1:length(genotypes)){
      
      #female and male genotype for this mating
      fSplit <- strsplit(genotypes[fi], "")[[1]]
      mSplit <- strsplit(genotypes[mi], "")[[1]]
      
      #split into parental alleles
      fGList <- list(allele1 = fSplit[1:nHom], allele2 = fSplit[(nHom+1):(2*nHom)] )
      mGList <- list(allele1 = mSplit[1:nHom], allele2 = mSplit[(nHom+1):(2*nHom)] )
      
      #set up allele and probability lists
      fAllele1 <- vector(mode = "list", length = nHom)
      fProbs1 <- vector(mode = "list", length = nHom)
      
      fAllele2 <- vector(mode = "list", length = nHom)
      fProbs2 <- vector(mode = "list", length = nHom)
      
      mAllele1 <- vector(mode = "list", length = nHom)
      mProbs1 <- vector(mode = "list", length = nHom)
      
      mAllele2 <- vector(mode = "list", length = nHom)
      mProbs2 <- vector(mode = "list", length = nHom)
      
      #fill female lists
      
      
      
      
      if(hCheck[fi]){
        #homing in females
        #lists of allele letter and probabilities
        for (i in 1:nHom){
          
          #female allele1
          if(fGList[[1]][i]=="W"){
            fAllele1[[i]] <- c("W", "H", "R", "S")
            fProbs1[[i]] <- homProbsList[[i]]$W
          } else if(fGList[[1]][i]=="H"){
            fAllele1[[i]] <- c("H", "S")
            fProbs1[[i]] <- homProbsList[[i]]$H
          } else if(fGList[[1]][i]=="R"){
            fAllele1[[i]] <- "R"
            fProbs1[[i]] <- homProbsList[[i]]$R
          } else if(fGList[[1]][i]=="S"){
            fAllele1[[i]] <- "S"
            fProbs1[[i]] <- homProbsList[[i]]$S
          }
          
          #female allele2
          if(fGList[[2]][i]=="W"){
            fAllele2[[i]] <- c("W", "H", "R", "S")
            fProbs2[[i]] <- homProbsList[[i]]$W
          } else if(fGList[[2]][i]=="H"){
            fAllele2[[i]] <- c("H", "S")
            fProbs2[[i]] <- homProbsList[[i]]$H
          } else if(fGList[[2]][i]=="R"){
            fAllele2[[i]] <- "R"
            fProbs2[[i]] <- homProbsList[[i]]$R
          } else if(fGList[[2]][i]=="S"){
            fAllele2[[i]] <- "S"
            fProbs2[[i]] <- homProbsList[[i]]$S
          }
          
        }
        
      } else {
        #no homing in females
        #lists of allele letter and probabilities
        for (i in 1:nHom){
          
          #female allele1
          if(fGList[[1]][i]=="W"){
            fAllele1[[i]] <- c("W", "S")
            fProbs1[[i]] <- noHomProbsList[[i]]$W
          } else if(fGList[[1]][i]=="H"){
            fAllele1[[i]] <- c("H", "S")
            fProbs1[[i]] <- noHomProbsList[[i]]$H
          } else if(fGList[[1]][i]=="R"){
            fAllele1[[i]] <- "R"
            fProbs1[[i]] <- noHomProbsList[[i]]$R
          } else if(fGList[[1]][i]=="S"){
            fAllele1[[i]] <- "S"
            fProbs1[[i]] <- noHomProbsList[[i]]$S
          }
          
          #female allele2
          if(fGList[[2]][i]=="W"){
            fAllele2[[i]] <- c("W", "S")
            fProbs2[[i]] <- noHomProbsList[[i]]$W
          } else if(fGList[[2]][i]=="H"){
            fAllele2[[i]] <- c("H", "S")
            fProbs2[[i]] <- noHomProbsList[[i]]$H
          } else if(fGList[[2]][i]=="R"){
            fAllele2[[i]] <- "R"
            fProbs2[[i]] <- noHomProbsList[[i]]$R
          } else if(fGList[[2]][i]=="S"){
            fAllele2[[i]] <- "S"
            fProbs2[[i]] <- noHomProbsList[[i]]$S
          }
          
        }
        
      }
      
      #fill male lists
      if(hCheck[mi]){
        #homing in males
        #lists om allele letter and probabilities
        for (i in 1:nHom){
          
          #male allele1
          if(mGList[[1]][i]=="W"){
            mAllele1[[i]] <- c("W", "H", "R", "S")
            mProbs1[[i]] <- homProbsList[[i]]$W
          } else if(mGList[[1]][i]=="H"){
            mAllele1[[i]] <- c("H", "S")
            mProbs1[[i]] <- homProbsList[[i]]$H
          } else if(mGList[[1]][i]=="R"){
            mAllele1[[i]] <- "R"
            mProbs1[[i]] <- homProbsList[[i]]$R
          } else if(mGList[[1]][i]=="S"){
            mAllele1[[i]] <- "S"
            mProbs1[[i]] <- homProbsList[[i]]$S
          }
          
          #male allele2
          if(mGList[[2]][i]=="W"){
            mAllele2[[i]] <- c("W", "H", "R", "S")
            mProbs2[[i]] <- homProbsList[[i]]$W
          } else if(mGList[[2]][i]=="H"){
            mAllele2[[i]] <- c("H", "S")
            mProbs2[[i]] <- homProbsList[[i]]$H
          } else if(mGList[[2]][i]=="R"){
            mAllele2[[i]] <- "R"
            mProbs2[[i]] <- homProbsList[[i]]$R
          } else if(mGList[[2]][i]=="S"){
            mAllele2[[i]] <- "S"
            mProbs2[[i]] <- homProbsList[[i]]$S
          }
          
        }
        
      } else {
        #no homing in males
        #lists om allele letter and probabilities
        for (i in 1:nHom){
          
          #male allele1
          if(mGList[[1]][i]=="W"){
            mAllele1[[i]] <- c("W", "S")
            mProbs1[[i]] <- noHomProbsList[[i]]$W
          } else if(mGList[[1]][i]=="H"){
            mAllele1[[i]] <- c("H", "S")
            mProbs1[[i]] <- noHomProbsList[[i]]$H
          } else if(mGList[[1]][i]=="R"){
            mAllele1[[i]] <- "R"
            mProbs1[[i]] <- noHomProbsList[[i]]$R
          } else if(mGList[[1]][i]=="S"){
            mAllele1[[i]] <- "S"
            mProbs1[[i]] <- noHomProbsList[[i]]$S
          }
          
          #male allele2
          if(mGList[[2]][i]=="W"){
            mAllele2[[i]] <- c("W", "S")
            mProbs2[[i]] <- noHomProbsList[[i]]$W
          } else if(mGList[[2]][i]=="H"){
            mAllele2[[i]] <- c("H", "S")
            mProbs2[[i]] <- noHomProbsList[[i]]$H
          } else if(mGList[[2]][i]=="R"){
            mAllele2[[i]] <- "R"
            mProbs2[[i]] <- noHomProbsList[[i]]$R
          } else if(mGList[[2]][i]=="S"){
            mAllele2[[i]] <- "S"
            mProbs2[[i]] <- noHomProbsList[[i]]$S
          }
          
        }
        
      }
      
      
      
      #get all combinations of those lists, separately letters and numbers, but in same order
      fKid1 <- expand.grid(fAllele1, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      fPKid1 <- expand.grid(fProbs1, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      fKid2 <- expand.grid(fAllele2, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      fPKid2 <- expand.grid(fProbs2, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      
      mKid1 <- expand.grid(mAllele1, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      mPKid1 <- expand.grid(mProbs1, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      mKid2 <- expand.grid(mAllele2, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      mPKid2 <- expand.grid(mProbs2, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      
      #add letters together, multiply probabilities
      fKid1Collapse <- do.call(what = stringi::stri_join, args = fKid1)
      fPKid1Collapse <- matrixStats::rowProds(x = as.matrix(fPKid1), rows = NULL, cols = NULL, na.rm = TRUE, method = "expSumLog")
      fKid2Collapse <- do.call(what = stringi::stri_join, args = fKid2)
      fPKid2Collapse <- matrixStats::rowProds(x = as.matrix(fPKid2), rows = NULL, cols = NULL, na.rm = TRUE, method = "expSumLog")
      
      mKid1Collapse <- do.call(what = stringi::stri_join, args = mKid1)
      mPKid1Collapse <- matrixStats::rowProds(x = as.matrix(mPKid1), rows = NULL, cols = NULL, na.rm = TRUE, method = "expSumLog")
      mKid2Collapse <- do.call(what = stringi::stri_join, args = mKid2)
      mPKid2Collapse <- matrixStats::rowProds(x = as.matrix(mPKid2), rows = NULL, cols = NULL, na.rm = TRUE, method = "expSumLog")
      
      #since these are 2 alleles in same parent, ofspring can't get both, so combine to 1 long list of all possible alleles
      # reorder allele labels, expand.grid calls them backwords from my definition
      fPoss <- stringi::stri_reverse(str = c(fKid1Collapse, fKid2Collapse))
      fProbsPoss <- c(fPKid1Collapse, fPKid2Collapse)
      
      mPoss <- stringi::stri_reverse(str = c(mKid1Collapse, mKid2Collapse))
      mProbsPoss <- c(mPKid1Collapse, mPKid2Collapse)
      
      #all combinations of male and female alleles
      offspringgenotypes <- expand.grid(fPoss, mPoss, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      offspringprobabilities <- expand.grid(fProbsPoss, mProbsPoss, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
      
      #recombine into genotypes and their probabilities, 2 lists in same order.
      # collapse is 2 to 1 because expand.grid orders vectors backwords from combinations and permutations above
      offspringgenocollapse <- do.call(what = stringi::stri_join, args = list(offspringgenotypes[,2], offspringgenotypes[,1]))
      
      offspringprobcollapse <- matrixStats::rowProds(x = as.matrix(offspringprobabilities), rows = NULL, cols = NULL, na.rm = TRUE, method = "expSumLog")/4
      
      
      
      #normalize probabilities
      #offspringprobcollapse <- offspringprobcollapse/4
      
      #reverse allele permutations that don't match allele combinations
      index <- which((offspringgenocollapse %in% genotypes)==FALSE)
      
      offspringgenocollapse[index] <- do.call(what = stringi::stri_join, args = list(offspringgenotypes[index,1], offspringgenotypes[index,2]))
      
      #set names on vector for better access
      nIndex <- match(x = offspringgenocollapse, table = genotypes)
      
      
     # offspringprobcollapse <- setNames(object = offspringprobcollapse, nm = offspringgenocollapse)
      
      
      
      #tMatrix[fi,mi, nIndex ] <- tMatrix[fi,mi, nIndex ] + offspringprobcollapse[nIndex]
      
      
      
      #store in matrix
      for (i in 1:length(offspringgenocollapse)){
        
        tMatrix[fi,mi, nIndex[i] ] <- tMatrix[fi,mi, nIndex[i] ] + offspringprobcollapse[i]
        
      }
      
    }
  }
  
  return(tMatrix)
  
}





