###############################################################################
#    ____        _           ____       _           
#   |  _ \  __ _(_)___ _   _|  _ \ _ __(_)_   _____ 
#   | | | |/ _` | / __| | | | | | | '__| \ \ / / _ \
#   | |_| | (_| | \__ \ |_| | |_| | |  | |\ V /  __/
#   |____/ \__,_|_|___/\__, |____/|_|  |_| \_/ \___|
#                      |___/                        
###############################################################################
#create generating function for Daisy Drive


MakeReference <- function(H=c(0.9, 0.8, 0.7),R=c(0.001, 0.001, 0.001), S=R/3, d=c(0.0001, 0.0001, 0.0001)){

  #H is homing rate. The length of this vector determines the number of pieces
  # in the daisy drive. Each drive can have the same or different rates. 

  #R is the NHEJ rate for deleterious alleles. Must be same length as H, 
  # can be the same or different values.
                            
  #S is the NHEJ rate for neutral alleles. Must be the same length as H, 
  # can be the same or different values.
  
  #d is the background mutation rate. Must be the same length as H, can
  # have the same or different values.
  
  gtype <- c("W", "H", "R", "S")
  
  #matrix to hold homing probs, then fill it
  homingProbs <- matrix(data = 0, nrow = 4, ncol = length(H), dimnames = list(gtype, NULL))
  cuttingProbs <- matrix(data = 0, nrow = 3, ncol = length(H), dimnames = list(gtype[-2], NULL))
  
  homingProbs[1, ] <- 1-d-H #chance to stay W is 1-homing-background mutation
  homingProbs[2, ] <- H*(1-R-S) #chance to become homing is H*1-H*R-H*S
  homingProbs[3, ] <- H*R   #NHEJ caused resistance, detrimentalt allele
  homingProbs[4, ] <- d+H*S #good resistant allele, from NHEJ and background mutation rate
  
  cuttingProbs[1, ] <- 1-d-H*(R+S) #chance to stay W, 1-homingrate*mutations-background
  cuttingProbs[2, ] <- H*R #chance to become R, cutting*NHEJ deleterious rate
  cuttingProbs[3, ] <- H*S+d #become S, cutting*NHEJ neutral + background
  
  
  #set up lists to hold probabilities
  mendProbsList <- vector(mode = "list", length = length(H))
  cutProbsList <- vector(mode = "list", length = length(H))
  homProbsList <- vector(mode = "list", length = length(H))
  
  #fill the lists
  for(i in 1:length(H)){
    mendProbsList[[i]]$W <- setNames(object = c(1-d[i], d[i]), nm = c("W", "S"))
    mendProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    mendProbsList[[i]]$R <- 1
    mendProbsList[[i]]$S <- 1
    
    cutProbsList[[i]]$W <- cuttingProbs[ ,i]
    cutProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    cutProbsList[[i]]$R <- 1
    cutProbsList[[i]]$S <- 1
    
    homProbsList[[i]]$W <- homingProbs[ ,i]
    homProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    homProbsList[[i]]$R <- 1
    homProbsList[[i]]$S <- 1
  }
  
  
  return(list(
    mendelian = mendProbsList, 
    cutting = cutProbsList, 
    homing = homProbsList))
  
}

hold <- MakeReference()

DaisyOffspring <- function(fGen, mGen, reference){
  #fGen is mother genotype
  #mGen is fathers genotype
  #reference is list of lists generated by MakeReference
  
  teststring <- "WWHWSS"
  #split mother genotype
  #This splits all characters.
  #the paste statement auto-replicates c(TRUE, FALSE), pulling odd values
  # from the first and even from the second, thereby getting every two added
  fSplit <- strsplit(x = teststring, split = "")[[1]]
  fDaisy <- paste0(fSplit[c(TRUE, FALSE)], fSplit[c(FALSE, TRUE)], collapse = NULL)
  
  
  #score them
  fscore <- c(FALSE, grepl(pattern = "H", x = fDaisy, ignore.case = FALSE, perl = FALSE, fixed = TRUE))
  
  
  nDaisies <- length(fDaisy)
  #setup offspring allele lists
  fAllele <- rep(x = list(vector(mode = "list", 2)), nDaisies)
  fProbs <- rep(x = list(vector(mode = "list", 2)), nDaisies)
  

  
  #this for loop runs over the number of daisy drive constructs
  for(i in 1:nDaisies){
    
    #3 if statements for 3 cases
    if((fscore[i]==FALSE && fscore[i+1]==FALSE) ||(fscore[i]==FALSE && fscore[i+1]==TRUE)){
      #FF or FT case
      
      for(j in 1:2){
        #get the single allele
        allele <- substr(x = fDaisy[i], start = j, stop = j)
        
        #Fill allele with letter and probs
        if(allele=="W"){
          fAllele[[i]][[j]] <- c("W","S")
          fProbs[[i]][[j]] <- reference$mendelian[[i]]$W
        } else if(allele=="H"){
          fAllele[[i]][[j]] <- c("H", "S")
          fProbs[[i]][[j]] <- reference$mendelian[[i]]$H
        } else if(allele=="R"){
          fAllele[[i]][[j]] <- "R"
          fProbs[[i]][[j]] <- reference$mendelian[[i]]$R
        } else if(allele=="S"){
          fAllele[[i]][[j]] <- "S"
          fProbs[[i]][[j]] <- reference$mendelian[[i]]$S
        }
        
      }#end of inner for loop
    } else if(fscore[i]==TRUE && fscore[i+1]==FALSE){
      #TF case
      
      for(j in 1:2){
        #get the single allele
        allele <- substr(x = fDaisy[i], start = j, stop = j)
        
        #Fill allele with letter and probs
        if(allele=="W"){
          fAllele[[i]][[j]] <- c("W","S")
          fProbs[[i]][[j]] <- reference$cutting[[i]]$W
        } else if(allele=="H"){
          fAllele[[i]][[j]] <- c("H", "S")
          fProbs[[i]][[j]] <- reference$cutting[[i]]$H
        } else if(allele=="R"){
          fAllele[[i]][[j]] <- "R"
          fProbs[[i]][[j]] <- reference$cutting[[i]]$R
        } else if(allele=="S"){
          fAllele[[i]][[j]] <- "S"
          fProbs[[i]][[j]] <- reference$cutting[[i]]$S
        }
        
      }#end of inner for loop
    } else if(fscore[i]==TRUE && fscore[i+1]==TRUE){
      #TT case
      
      for(j in 1:2){
        #get the single allele
        allele <- substr(x = fDaisy[i], start = j, stop = j)
        
        #Fill allele with letter and probs
        if(allele=="W"){
          fAllele[[i]][[j]] <- c("W","S")
          fProbs[[i]][[j]] <- reference$homing[[i]]$W
        } else if(allele=="H"){
          fAllele[[i]][[j]] <- c("H", "S")
          fProbs[[i]][[j]] <- reference$homing[[i]]$H
        } else if(allele=="R"){
          fAllele[[i]][[j]] <- "R"
          fProbs[[i]][[j]] <- reference$homing[[i]]$R
        } else if(allele=="S"){
          fAllele[[i]][[j]] <- "S"
          fProbs[[i]][[j]] <- reference$homing[[i]]$S
        }
        
      }#end of inner for loop
    }#end else if statements

  }#end of outermost for loop
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
}






test <- vector(mode = "list", 2)
test <- lapply(1:2, function(x){vector(mode = "list", length = 2)})
test <- rep(x = list(vector(mode = "list", 2)), 2)


for(i in 1:2){
  for(j in 1:2){
    
    if(j==1){
      test[[i]][[j]] <- j
    } else if (j==2){
      
      test[[i]][[j]] <- c("A", "B")
    }
    
    
  }
  
  
  
}
























