# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
MultiplexOffspring_mLoci_C <- function(fGen, mGen, reference) {
    .Call('_mPlexRCpp_MultiplexOffspring_mLoci_C', PACKAGE = 'mPlexRCpp', fGen, mGen, reference)
}

