# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Daisy Drive Offspring
#'
#' Create a list of offspring genotypes and their probabilities
#'
#' @usage DaisyOffspring(fGen, mGen, reference)
#'
#' @param fGen Female genotype
#' @param mGen Male genotype
#' @param reference Offspring reference list
#'
#' @details Using the reference generated by \code{\link{MakeReference_DaisyDrive}},
#' this function expands the possible genotypes of the offspring and the ratios
#' that they occur. Similar to \code{\link{MultiplexOffspring_mLoci}} and
#' \code{\link{MultiplexOffspring_oLocus}}.
#'
#' @return List(Alleles, Probabilities)
#'
#' @examples
#' ref <- MakeReferenceDaisy(H = 0.9, R = 0, S = 0, d = .001)
#' fGen <- "WW"
#' mGen <- "WW"
#'
#' DaisyOffspring(fGen, mGen, ref)
#'
#' @export
DaisyOffspring_C <- function(fGen, mGen, reference) {
    .Call('_mPlexRCpp_DaisyOffspring_C', PACKAGE = 'mPlexRCpp', fGen, mGen, reference)
}

#' mPlex Multiple Loci Offspring
#'
#' Create a list of offspring genotypes and their probabilities
#'
#' @usage MultiplexOffspring_mLoci(fGen, mGen, reference)
#'
#' @param fGen Female genotype
#' @param mGen Male genotype
#' @param reference Offspring reference list
#'
#' @details Using the reference generated by \code{\link{MakeReference_Multiplex_mLoci}},
#' this function expands the possible genotypes of the offspring and the ratios
#' that they occur. Similar to \code{\link{DaisyOffspring}} and
#' \code{\link{MultiplexOffspring_oLocus}}.
#'
#' @return List(Alleles, Probabilities)
#'
#' @examples
#' ref <- MakeReference_Multiplex_mLoci(H = 0.98, R = 0.001, S = 0.0003, d = .00001)
#' fGen <- "WW"
#' mGen <- "WW"
#'
#' MultiplexOffspring_mLoci(fGen, mGen, ref)
#'
#' @export
MultiplexOffspring_mLoci_C <- function(fGen, mGen, reference) {
    .Call('_mPlexRCpp_MultiplexOffspring_mLoci_C', PACKAGE = 'mPlexRCpp', fGen, mGen, reference)
}

#' mPlex Single Locus Offspring
#'
#' Create a list of offspring genotypes and their probabilities
#'
#' @usage MultiplexOffspring_oLocus_C(fGen, mGen, reference)
#'
#' @param fGen Female genotype
#' @param mGen Male genotype
#' @param reference Offspring reference list
#'
#' @details Using the reference generated by \code{\link{MakeReference_Multiplex_oLocus}},
#' this function expands the possible genotypes of the offspring and the ratios
#' that they occur. Similar to \code{\link{DaisyOffspring}} and
#' \code{\link{MultiplexOffspring_mLoci}}.
#'
#' @return List(Alleles, Probabilities)
#'
#' @examples
#' ref <- MakeReference_Multiplex_oLocus(H = 0.98, R = 0.001, S = 0.0003, d = .00001)
#' fGen <- "WW"
#' mGen <- "WW"
#'
#' MultiplexOffspring_oLocus_C(fGen, mGen, ref)
#'
#' @export
MultiplexOffspring_oLocus_C <- function(fGen, mGen, reference) {
    .Call('_mPlexRCpp_MultiplexOffspring_oLocus_C', PACKAGE = 'mPlexRCpp', fGen, mGen, reference)
}

