###############################################################################
#    __  __       _ _   _       _                      _
#   |  \/  |_   _| | |_(_)_ __ | | _____  __      ___ | |    ___   ___ _   _ ___
#   | |\/| | | | | | __| | '_ \| |/ _ \ \/ /____ / _ \| |   / _ \ / __| | | / __|
#   | |  | | |_| | | |_| | |_) | |  __/>  <_____| (_) | |__| (_) | (__| |_| \__ \
#   |_|  |_|\__,_|_|\__|_| .__/|_|\___/_/\_\     \___/|_____\___/ \___|\__,_|___/
#                        |_|
###############################################################################

#' mPlex One Locus Offspring Reference
#'
#' Create a list specifying the offspring probability distribution.
#'
#' @usage MakeReference_Multiplex_oLocus(H, R, S, d)
#'
#' @param H Vector of homing rates for each drive piece
#' @param R Vector of deleterious allele generation rates
#' @param S Vector of neutral allele generation rates
#' @param d Vector of background mutation rates at each locus
#'
#' @details This function creates a reference list for \code{\link{MultiplexOffspring_oLocus}}.
#' It assumes multiple targeting gRNAs for 1 locus, all targets segregate together.
#' The length of each allele is specified by the length of H. R, S, and d must
#' be the same length as H, but will generally be the same number replicated that
#' many times. It is assumed that S is R/3, but this can be varied.
#' This function is similar to \code{\link{MakeReference_DaisyDrive}} and
#' \code{\link{MakeReference_Multiplex_mLoci}}
#'
#' @return list of homing and mendelian genotypes and rates
#'
#' @examples
#' H <- c(0.9,0.4,0.7) # This drive has 3 targets at 1 locus
#' R <- c(0.001, 0.002, 0.003)
#' S <- c(0.0003, 0.0006, 0.001)
#' d <- c(0.0001, 0.0001, 0.0001)
#'
#' MakeReference_Multiplex_oLocus(H,R,S,d)
#'
#' @export
MakeReference_Multiplex_oLocus <- function(H=c(0.9),R=c(0.0), S=R/3, d=c(0.0001)){
  #H is homing rate. The length of this vector determines the number of loci
  # in the multiplex drive. Each drive can have the same or different rates.

  #R is the NHEJ rate for deleterious alleles. Must be same length as H,
  # can be the same or different values.

  #S is the NHEJ rate for neutral alleles. Must be the same length as H,
  # can be the same or different values.

  #d is the background mutation rate. Must be the same length as H, can
  # have the same or different values.



  #Safety checks
  if(any( c(length(H),length(R), length(S), length(d)) != length(H))){
    return(cat("All inputs must be the same length!\n",
           "i.e. length(H) == length(R) == length(S) == length(d)"))
  }
  if(any(H>1, R>1, S>1, d>1)){
    return(cat("All rates must be less than or equal to 1\n"))
  }
  if(any((d+H) > 1)){
    return(cat("Homing rates plus background mutation rates must be <= 1\n",
           "i.e. H+d <= 1\n"))
  }
  if(any((R+S) > 1)){
    return(cat("Negative and neutral repair rates must sum to <= 1\n",
           "i.s. R+S <= 1"))
  }


  #setup allele letters
  #W = Wild-type
  #H = Homing
  #R = Deleterious resistant
  #S = Neutral resistant
  gtype <- c("W", "H", "R", "S")

  #matrix to hold homing probs, then fill it
  homingProbs <- matrix(data = 0, nrow = 4, ncol = length(H), dimnames = list(gtype, NULL))

  homingProbs[1, ] <- 1-d-H #chance to stay W is 1-homing-background mutation
  homingProbs[2, ] <- H*(1-R-S) #chance to become homing is H*1-H*R-H*S
  homingProbs[3, ] <- H*R   #NHEJ caused resistance, detrimentalt allele
  homingProbs[4, ] <- d+H*S #good resistant allele, from NHEJ and background mutation rate

  #set up lists to hold probabilities
  mendProbsList <- vector(mode = "list", length = length(H))
  homProbsList <- vector(mode = "list", length = length(H))

  #fill the lists
  for(i in 1:length(H)){
    #Mendelian Probabilities
    mendProbsList[[i]]$W <- setNames(object = c(1-d[i], d[i]), nm = c("W", "S"))
    mendProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    mendProbsList[[i]]$R <- 1
    mendProbsList[[i]]$S <- 1

    #Homing Probabilities
    homProbsList[[i]]$W <- homingProbs[ ,i]
    homProbsList[[i]]$H <- setNames(object = c(1-d[i], d[i]), nm = c("H", "S"))
    homProbsList[[i]]$R <- 1
    homProbsList[[i]]$S <- 1
  }

  return(list(
    mendelian = mendProbsList,
    homing = homProbsList))

}

#' mPlex One Locus Offspring
#'
#' Create a list of offspring genotypes and their probabilities
#'
#' @usage MultiplexOffspring_oLocus(fGen, mGen, reference)
#'
#' @param fGen Female genotype
#' @param mGen Male genotype
#' @param reference Offspring reference list
#'
#' @details Using the reference generated by \code{\link{MakeReference_Multiplex_oLocus}},
#' this function expands the possible genotypes of the offspring and the ratios
#' that they occur. Similar to \code{\link{DaisyOffspring}} and
#' \code{\link{MultiplexOffspring_mLoci}}.
#'
#' @return List(Alleles, Probabilities)
#'
#' @examples
#' ref <- MakeReferenceDaisy(H = 0.98, R = 0.001, S = 0.0003, d = .00001)
#' fGen <- "WW"
#' mGen <- "WW"
#'
#' MultiplexOffspring_oLocus(fGen, mGen, ref)
#'
#' @export
MultiplexOffspring_oLocus <- function(fGen, mGen, reference){

  if(nchar(fGen) != nchar(mGen)){
    return(cat("Critters have different number of loci.\nCheck their genotypes."))
  }

  #split genotypes
  #This splits all characters.
  private$fSplit <- strsplit(x = fGen, split = "")[[1]]
  private$mSplit <- strsplit(x = mGen, split = "")[[1]]

  #get number of alleles. Divide by 2 is because diploid
  private$numAlleles <- length(private$fSplit)/2

  #the paste statement combines all targets in the first loci and all targets
  #  in the second loci into 2 complete alleles
  private$momAlleles <- list(allele1 = private$fSplit[1:private$numAlleles], allele2 = private$fSplit[(private$numAlleles+1):(2*private$numAlleles)] )
  private$dadAlleles <- list(allele1 = private$mSplit[1:private$numAlleles], allele2 = private$mSplit[(private$numAlleles+1):(2*private$numAlleles)] )

  #score them, assumes fGen and mGen are 1 character string, not a list of things
  #  If I stop pasting alleles together, we may have to change this!!
  private$fScore <- grepl(pattern = "H", x = fGen, ignore.case = FALSE, perl = FALSE, fixed = TRUE)
  private$mScore <- grepl(pattern = "H", x = mGen, ignore.case = FALSE, perl = FALSE, fixed = TRUE)

  #setup offspring allele lists
  # assuem diploid organism with private$numAlleles homing sites
  private$fAllele <- rep(x = list(vector(mode = "list", private$numAlleles)), 2)
  private$fProbs <- rep(x = list(vector(mode = "list", private$numAlleles)), 2)
  private$mAllele <- rep(x = list(vector(mode = "list", private$numAlleles)), 2)
  private$mProbs <- rep(x = list(vector(mode = "list", private$numAlleles)), 2)

  #Females!
  if(private$fScore) {
    #if homing allele present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:private$numAlleles){
        #Fill target with letter and probs
        if(private$momAlleles[[i]][[j]]=="W"){
          private$fAllele[[i]][[j]] <- c("W","H","R","S")
          private$fProbs[[i]][[j]] <- reference$homing[[j]]$W
        } else if(private$momAlleles[[i]][[j]]=="H"){
          private$fAllele[[i]][[j]] <- c("H", "S")
          private$fProbs[[i]][[j]] <- reference$homing[[j]]$H
        } else if(private$momAlleles[[i]][[j]]=="R"){
          private$fAllele[[i]][[j]] <- "R"
          private$fProbs[[i]][[j]] <- reference$homing[[j]]$R
        } else if(private$momAlleles[[i]][[j]]=="S"){
          private$fAllele[[i]][[j]] <- "S"
          private$fProbs[[i]][[j]] <- reference$homing[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop

  } else {
    #if homing allele not present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:private$numAlleles){
        #Fill target with letter and probs
        if(private$momAlleles[[i]][[j]]=="W"){
          private$fAllele[[i]][[j]] <- c("W","S")
          private$fProbs[[i]][[j]] <- reference$mendelian[[j]]$W
        } else if(private$momAlleles[[i]][[j]]=="H"){
          private$fAllele[[i]][[j]] <- c("H", "S")
          private$fProbs[[i]][[j]] <- reference$mendelian[[j]]$H
        } else if(private$momAlleles[[i]][[j]]=="R"){
          private$fAllele[[i]][[j]] <- "R"
          private$fProbs[[i]][[j]] <- reference$mendelian[[j]]$R
        } else if(private$momAlleles[[i]][[j]]=="S"){
          private$fAllele[[i]][[j]] <- "S"
          private$fProbs[[i]][[j]] <- reference$mendelian[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
  }#end Female if statement

  #Males!
  if(private$mScore) {
    #if homing allele present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:private$numAlleles){
        #Fill target with letter and probs
        if(private$dadAlleles[[i]][[j]]=="W"){
          private$mAllele[[i]][[j]] <- c("W","H","R","S")
          private$mProbs[[i]][[j]] <- reference$homing[[j]]$W
        } else if(private$dadAlleles[[i]][[j]]=="H"){
          private$mAllele[[i]][[j]] <- c("H", "S")
          private$mProbs[[i]][[j]] <- reference$homing[[j]]$H
        } else if(private$dadAlleles[[i]][[j]]=="R"){
          private$mAllele[[i]][[j]] <- "R"
          private$mProbs[[i]][[j]] <- reference$homing[[j]]$R
        } else if(private$dadAlleles[[i]][[j]]=="S"){
          private$mAllele[[i]][[j]] <- "S"
          private$mProbs[[i]][[j]] <- reference$homing[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop

  } else {
    #if homing allele not present
    #loop over alleles, assume diploid
    for(i in 1:2){
      #loop over targets within locus
      for(j in 1:private$numAlleles){
        #Fill target with letter and probs
        if(private$dadAlleles[[i]][[j]]=="W"){
          private$mAllele[[i]][[j]] <- c("W","S")
          private$mProbs[[i]][[j]] <- reference$mendelian[[j]]$W
        } else if(private$dadAlleles[[i]][[j]]=="H"){
          private$mAllele[[i]][[j]] <- c("H", "S")
          private$mProbs[[i]][[j]] <- reference$mendelian[[j]]$H
        } else if(private$dadAlleles[[i]][[j]]=="R"){
          private$mAllele[[i]][[j]] <- "R"
          private$mProbs[[i]][[j]] <- reference$mendelian[[j]]$R
        } else if(private$dadAlleles[[i]][[j]]=="S"){
          private$mAllele[[i]][[j]] <- "S"
          private$mProbs[[i]][[j]] <- reference$mendelian[[j]]$S
        }#end if string
      }#end target loop
    }#end allele loop
  }#end Female if statement


  private$fAllLoci <- vector(mode = "list", length = 2)
  private$fProbsLoci <- vector(mode = "list", length = 2)
  private$mAllLoci <- vector(mode = "list", length = 2)
  private$mProbsLoci <- vector(mode = "list", length = 2)

  for(i in 1:2){
    #expand female alleles and probs
    private$holdAllOne <- expand.grid(private$fAllele[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    private$holdProbOne <- expand.grid(private$fProbs[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)

    #expand male alleles and probs
    private$holdAllTwo <- expand.grid(private$mAllele[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    private$holdProbTwo <- expand.grid(private$mProbs[[i]], KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)

    #paste things in reverse
    private$fAllLoci[[i]] <- do.call(what = paste0, c(private$holdAllOne[, private$numAlleles:1,drop=FALSE], collapse = NULL))
    private$fProbsLoci[[i]] <- apply(X = private$holdProbOne, MARGIN = 1, FUN = prod)

    private$mAllLoci[[i]] <- do.call(what = paste0, c(private$holdAllTwo[, private$numAlleles:1,drop=FALSE], collapse = NULL))
    private$mProbsLoci[[i]] <- apply(X = private$holdProbTwo, MARGIN = 1, FUN = prod)

  }


  #unlist so that alleles within parent don't combine, then expand all
  #  combinations of male/female alleles
  private$outAList <- expand.grid(unlist(private$fAllLoci), unlist(private$mAllLoci), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
  private$outPList <- expand.grid(unlist(private$fProbsLoci), unlist(private$mProbsLoci), KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)

  private$outAList <- do.call(what = paste0, c(private$outAList, collapse = NULL))
  private$outPList <- apply(X = private$outPList, MARGIN = 1, FUN = prod)
  #could do hold[,1]*hold[,2]

  #aggregate and return
  private$aggregateHold <- aggregate(private$outPList~private$outAList, data=data.frame(private$outAList, private$outPList), FUN=sum)


  #get proper type and normalize, then return as list.
  private$offspring <- list(
    Alleles = as.character(private$aggregateHold$'private$outAList'),
    Probabilities = private$aggregateHold$'private$outPList'/sum(private$aggregateHold$'private$outPList')
  )

}
